-- MySQL Script generated by MySQL Workbench
-- 10/09/16 15:08:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema libreria2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria2` DEFAULT CHARACTER SET utf8 ;
USE `libreria2` ;

-- -----------------------------------------------------
-- Table `libreria2`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`sucursales` (
  `idsucursal` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(300) NULL,
  `telefono` VARCHAR(45) NULL,
  `encargado` VARCHAR(100) NULL,
  PRIMARY KEY (`idsucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`cargos` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dui` VARCHAR(45) NULL,
  `nit` VARCHAR(45) NULL,
  `idcargo` INT NULL,
  `idsucursal` INT NULL,
  `telefono` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuarios_sucursales_idx` (`idsucursal` ASC),
  INDEX `fk_usuarios_campos1_idx` (`idcargo` ASC),
  CONSTRAINT `fk_usuarios_sucursales`
    FOREIGN KEY (`idsucursal`)
    REFERENCES `libreria2`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_campos1`
    FOREIGN KEY (`idcargo`)
    REFERENCES `libreria2`.`cargos` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`presentaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`presentaciones` (
  `idpresentacion` INT NOT NULL AUTO_INCREMENT,
  `presentacion_compra` VARCHAR(45) NULL,
  `presentacion_venta` VARCHAR(45) NULL,
  `cantidad_inter_compra` INT NULL,
  `nombre_presentacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idpresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`proveedores` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `cod_proveedor` VARCHAR(45) NULL,
  `nombre_proveedor` VARCHAR(100) NULL,
  `dui` VARCHAR(45) NULL,
  `nit` VARCHAR(45) NULL,
  `ncr` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `cod_producto` INT NULL,
  `nom_producto` VARCHAR(45) NULL,
  `precio_compra` DOUBLE NULL,
  `precio_venta` DOUBLE NULL,
  `fecha_ingreso` DATE NULL,
  `idpresentacion` INT NULL,
  `idproveedor` INT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_productos_presentaciones1_idx` (`idpresentacion` ASC),
  INDEX `fk_productos_proveedores1_idx` (`idproveedor` ASC),
  CONSTRAINT `fk_productos_presentaciones1`
    FOREIGN KEY (`idpresentacion`)
    REFERENCES `libreria2`.`presentaciones` (`idpresentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_proveedores1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `libreria2`.`proveedores` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`descuentos` (
  `iddescuento` INT NOT NULL AUTO_INCREMENT,
  `tipo_descuento` VARCHAR(45) NULL,
  `descuento` DOUBLE NULL,
  PRIMARY KEY (`iddescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `cod_clientes` VARCHAR(45) NULL,
  `nombre_cliente` VARCHAR(100) NULL,
  `direccion` VARCHAR(300) NULL,
  `dui` VARCHAR(45) NULL,
  `nit` VARCHAR(45) NULL,
  `razon_social` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_ingreso` DATE NULL,
  `iddescuento` INT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_clientes_descuentos1_idx` (`iddescuento` ASC),
  CONSTRAINT `fk_clientes_descuentos1`
    FOREIGN KEY (`iddescuento`)
    REFERENCES `libreria2`.`descuentos` (`iddescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`tipos_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`tipos_facturas` (
  `idtipo_factura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_factura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`facturas` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `numero_factura` INT NULL,
  `fecha_factura` DATE NULL,
  `ncr` VARCHAR(45) NULL,
  `idtipofactura` INT NULL,
  `idusuario` INT NULL,
  `monto_total_neto` DOUBLE NULL,
  `descuento_iva` DOUBLE NULL,
  `descuento_renta` DOUBLE NULL,
  `monto_total` DOUBLE NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_facturas_tipos_facturas1_idx` (`idtipofactura` ASC),
  INDEX `fk_facturas_usuarios1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_facturas_tipos_facturas1`
    FOREIGN KEY (`idtipofactura`)
    REFERENCES `libreria2`.`tipos_facturas` (`idtipo_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `libreria2`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`detalles_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`detalles_compras` (
  `iddetalle_compra` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NULL,
  `cantidad` INT NULL,
  `precio_compra` DOUBLE NULL,
  `total` DOUBLE NULL,
  `idfactura` INT NULL,
  PRIMARY KEY (`iddetalle_compra`),
  INDEX `fk_detalles_compras_facturas1_idx` (`idfactura` ASC),
  INDEX `fk_detalles_compras_productos1_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detalles_compras_facturas1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `libreria2`.`facturas` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_compras_productos1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `libreria2`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`compras` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATE NULL,
  `idfactura` INT NULL,
  `idsucursal` INT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compras_facturas1_idx` (`idfactura` ASC),
  INDEX `fk_compras_sucursales1_idx` (`idsucursal` ASC),
  CONSTRAINT `fk_compras_facturas1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `libreria2`.`facturas` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_sucursales1`
    FOREIGN KEY (`idsucursal`)
    REFERENCES `libreria2`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`tickets` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `correlativo` INT NULL,
  `fecha` DATE NULL,
  `idusuario` INT NULL,
  `monto_total_neto` DOUBLE NULL,
  `descuentos` DOUBLE NULL,
  `monto_total` DOUBLE NULL,
  PRIMARY KEY (`idticket`),
  INDEX `fk_tickets_usuarios1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_tickets_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `libreria2`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`detalles_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`detalles_ventas` (
  `iddetalle_venta` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NULL,
  `cantidad` INT NULL,
  `precio_venta` DOUBLE NULL,
  `total` DOUBLE NULL,
  `idfactura` INT NULL,
  `idticket` INT NULL,
  PRIMARY KEY (`iddetalle_venta`),
  INDEX `fk_detalles_ventas_tickets1_idx` (`idticket` ASC),
  INDEX `fk_detalles_ventas_facturas1_idx` (`idfactura` ASC),
  INDEX `fk_detalles_ventas_productos1_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detalles_ventas_tickets1`
    FOREIGN KEY (`idticket`)
    REFERENCES `libreria2`.`tickets` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_ventas_facturas1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `libreria2`.`facturas` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_ventas_productos1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `libreria2`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`formas_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`formas_pagos` (
  `idforma_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`idforma_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`ventas` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idforma_forma_pago` INT NULL,
  `idsucursal` INT NULL,
  `fecha` DATE NULL,
  `idfactura` INT NULL,
  `idticket` INT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_ventas_formas_pagos1_idx` (`idforma_forma_pago` ASC),
  INDEX `fk_ventas_sucursales1_idx` (`idsucursal` ASC),
  INDEX `fk_ventas_facturas1_idx` (`idfactura` ASC),
  INDEX `fk_ventas_tickets1_idx` (`idticket` ASC),
  CONSTRAINT `fk_ventas_formas_pagos1`
    FOREIGN KEY (`idforma_forma_pago`)
    REFERENCES `libreria2`.`formas_pagos` (`idforma_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_sucursales1`
    FOREIGN KEY (`idsucursal`)
    REFERENCES `libreria2`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_facturas1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `libreria2`.`facturas` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_tickets1`
    FOREIGN KEY (`idticket`)
    REFERENCES `libreria2`.`tickets` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`inventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`inventarios` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NULL,
  `idsucursal` INT NULL,
  `existencias` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idinventario`),
  INDEX `fk_inventarios_productos1_idx` (`idproducto` ASC),
  INDEX `fk_inventarios_sucursales1_idx` (`idsucursal` ASC),
  CONSTRAINT `fk_inventarios_productos1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `libreria2`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventarios_sucursales1`
    FOREIGN KEY (`idsucursal`)
    REFERENCES `libreria2`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria2`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria2`.`devoluciones` (
  `iddevolucione` INT NOT NULL AUTO_INCREMENT,
  `idfactura` INT NULL,
  `idticket` INT NULL,
  `idproducto` INT NULL,
  `total_descuento` DOUBLE NULL,
  `idusuario` INT NULL,
  PRIMARY KEY (`iddevolucione`),
  INDEX `fk_devoluciones_facturas1_idx` (`idfactura` ASC),
  INDEX `fk_devoluciones_tickets1_idx` (`idticket` ASC),
  INDEX `fk_devoluciones_productos1_idx` (`idproducto` ASC),
  INDEX `fk_devoluciones_usuarios1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_devoluciones_facturas1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `libreria2`.`facturas` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devoluciones_tickets1`
    FOREIGN KEY (`idticket`)
    REFERENCES `libreria2`.`tickets` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devoluciones_productos1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `libreria2`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devoluciones_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `libreria2`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
